[package]
name = "moly-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.moly]
surface = "protocol"
stability = "experimental"

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[lints]
workspace = true
